language: shell
os: linux
dist: bionic
before_install:
  - wget https://raw.githubusercontent.com/kward/shunit2/v2.1.8/shunit2
jobs:
  include:
  - stage: Tests
  - name: Smoke Tests
    script: ./dummy_test.sh
script:
  - shellcheck virtinit

