language: shell
os: linux
dist: bionic
jobs:
  include:
  - stage: static analysis
    name: shellcheck
    script: shellcheck virtinit *.sh
  - stage: tests
    name: test virtinit script
    before_install:
      - ./install-test-dependencies.sh
    script: ./dummy_test.sh

