language: shell
os: linux
dist: bionic
jobs:
  include:
  - stage: tests

    name: static analysis
    script: shellcheck virtinit *.sh

    name: test virtinit script
    before_install:
      - ./install-test-dependencies.sh
    before_script:
      - ./dummy_test.sh
    script:
      - ./before_test.sh
      - ./virtinit
      - ./after_test.sh
