---
- name: virtinit
  hosts: localhost
  tasks:
  - name: Dependencies
    block:
      - apt:
          pkg:
          - python3-apt
    become: true
    tags: dependencies

  - name: Virtualization Technologies Check
    block:
      - name: APT install cpu-checker
        apt:
          name: cpu-checker
        become: true
      - command: kvm-ok
        register: result
        ignore_errors: true
        become: true
      - debug: var=result.stdout_lines
      - fail:
          msg: Enable virtualization (see above) and then re-run virtinit.
        when: result is failure
    tags: cpucheck

  - name: VirtualBox
    vars:
      virtualbox_key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      virtualbox_repo_url: https://download.virtualbox.org/virtualbox/debian
    block:
      - apt_key:
          url: "{{ virtualbox_key_url }}"
      - apt_repository:
          repo: "deb [arch=amd64] {{ virtualbox_repo_url }} {{ ansible_distribution_release}} contrib"
      - apt:
          name: virtualbox-6.1
    tags: virtualbox
    become: true

