---
- name: virtinit
  hosts: localhost
  tasks:

  - name: Virtualization Technologies Check
    block:
      - name: APT install cpu-checker
        apt:
          name: cpu-checker
        become: true
      - command: kvm-ok
        register: result
        ignore_errors: true
        become: true
      - debug: var=result.stdout_lines
      - fail:
          msg: Enable virtualization (see above) and then re-run virtinit.
        when: result is failure
    tags: cpucheck

  - name: VirtualBox
    vars:
      virtualbox_key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      virtualbox_repo_url: https://download.virtualbox.org/virtualbox/debian
    block:
      - apt_key:
          url: "{{ virtualbox_key_url }}"
      - apt_repository:
          repo: "deb [arch=amd64] {{ virtualbox_repo_url }} {{ ansible_distribution_release}} contrib"
      - apt:
          name: virtualbox-6.0
    tags: virtualbox
    become: true


  - name: Remove unofficial Vagrant apt repository key
    apt_key:
      id: AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
      keyserver: keyserver.ubuntu.com
      state: absent
    become: yes

  - name: Remove unofficial Vagrant apt repository
    vars:
      repository_url: https://vagrant-deb.linestarve.com/
    apt_repository:
      repo: "deb {{ repository_url }} any main"
      state: absent

  - name: Add Vagrant apt repository key
    apt_key:
      id: E8A032E094D8EB4EA189D270DA418C88A3219F7B
      url: https://apt.releases.hashicorp.com/gpg

  - name: Add Vagrant apt repository
    vars:
      repository_url: https://apt.releases.hashicorp.com
    apt_repository:
      repo: "deb [arch=amd64] {{repository_url}} {{ ansible_distribution_release }} main"
    become: yes

  - name: Install Vagrant
    apt:
      name: vagrant
    become: true
