#!/bin/sh
# virtinit

# Most of the virtinit script is implemented as an Ansible playbook which
# runs locally. First we need to bootstrap Ansible with Python3 support.

# APT Cache
# First update the apt cache so that system packages can be found.
sudo apt update

# pip3
# Install pip3 from system packages 
# https://packages.ubuntu.com/python3-pip
sudo apt install --assume-yes python3-pip

# Ansible
PKG_ANSIBLE=ansible
# The apt version of Ansible from the Ubuntu repositories uses Python 2 so it
# is removed if already installed.
# https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-ubuntu
# https://packages.ubuntu.com/ansible
# https://launchpad.net/~ansible/+archive/ubuntu/ansible
sudo apt purge --assume-yes --auto-remove $PKG_ANSIBLE

# Install the pip version of Ansible which uses Python 3.
# https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html
pip3 install $PKG_ANSIBLE

# playbook
#PLAYBOOK=main.yml
# Hand over to Ansible for the rest of the configuration.
#echo "Run ansible playbook."
#ansible-playbook $PLAYBOOK
